### PR TITLE
Allow changing of body height via table options

### PR DESCRIPTION
**Pull request by Tempus35**

### CODE REVIEW

**Comment by amcdnl** [comment]
Discussion in Gitter:

> This is a internal property. The property is set at runtime by a calculation of the height of the element. Verify this: https://github.com/swimlane/angular2-data-table/blob/master/src/components/DataTable.ts#L128

**Comment by amcdnl** [comment]
@Tempus35 any updates on this?

**Comment by Tempus35** [comment]
Not yet, sorry been busy. I will look more into it this afternoon or tomorrow though.

**Comment by Tempus35** [comment]
So I did some quick testing, the height of the table is indeed calculated on runtime by amount of rows and row height. Further more the bodyHeight, when set with this modified code, does not change anything. I am closing this.

**Pull request closed without merging**
