### PR TITLE
Column resize sometimes gives weird behaviour on mouse resize/click

### PR DESCRIPTION
**Pull request by jtomaszewski**
If you resize column with a mouse click & drag a couple of times, sometimes it jumps to a weird position or doesn't "unclick" at all. More details: https://drive.google.com/file/d/0B5-IASgGnqwdN214NmVrWFkzb3M/view (problems visible from ~0:20). 

After a couple of resizing clicks, the sort button stops working as well - you have to click on it multiple times, sometimes the click resizes the column instead of changing sort direction - etc.

Any ideas what exactly can be wrong? ;s

### CODE REVIEW

**Comment by jtomaszewski** [comment]
Fixed in the commits above. Ready to merge.

**Comment by jtomaszewski** [comment]
O, sorry, not yet, its not fixed. The problem appeared when `event.movementX` was equal to 0 and so then variable jumped to `(event.screenX - this.prevScreenX)`. I'll make push force better commit in a sec.

**Comment by jtomaszewski** [comment]
Now it's fixed.

**Comment by jtomaszewski** [comment]
Sorry for spamming. Previous way just wasn't good and was buggy. Now I simplified it and it works 100%.

**Comment by amcdnl** [comment]
You're awesome! :)

**Pull request merged**
