### PR TITLE
Use ChangeDetectionStrategy.OnPush in BodyCell component

### PR DESCRIPTION
**Pull request by jtomaszewski**

### CODE REVIEW

**Comment by amcdnl** [comment]
Need to rebase :(.

Does it work with the previous issue I reverted it to?

**Comment by jtomaszewski** [comment]
Yeah, it should work with the previous issue.

**Comment by jtomaszewski** [comment]
Although right now you made bodycell dependent on state, so we'd need to refactor the whole thing a bit to accomplish that ( https://github.com/swimlane/angular2-data-table/pull/144/commits/d16833172189d4fec4a18f959b9bbb5407775f96#diff-6c5fe72c2cab8659bc1ddbfa686ed2f9R29 ).

**Comment by amcdnl** [comment]
I think we could set that property via the parent or pass it down and it would be fine.

**Comment by amcdnl** [comment]
Closing this given comments above.

**Pull request closed without merging**
