### PR TITLE
fix Column header on horizontal scroll

### PR DESCRIPTION
**Pull request by wor-k**

### CODE REVIEW

**Comment by amcdnl** [comment]
What issue does this code solve?

**Comment by wor-k** [comment]
Its a #25.

**Comment by amcdnl** [comment]
Gotcha; I'm planning on addressing this as part of a larger change.  I'm essentially going to port my code from my ng1 table - https://github.com/swimlane/angular-data-table/blob/master/src/components/header/HeaderController.js#L64

Let me look over this and I'll provide feedback and/or merge :). Thanks!

**Comment by wor-k** [comment]
It's ok. do what you plan. I'm really like this library.

**Comment by amcdnl** [comment]
Thank you 👍 ! I'll keep you posted, I have to get quite a few items done before ngAir on the 16th this will be part of it for sure!

**Pull request closed without merging**
