### PR TITLE
Allow configuration table Height in pixels with TableOptions property tableHeight.

### PR DESCRIPTION
**Pull request by amiller29au**
I wanted a way to enable the table height to be configurable and could not find an option to do this.

I using the table option with scrolling, not pagination.

### CODE REVIEW

**Comment by amcdnl** [comment]
Cool, thanks for the contribution!

**Comment by amcdnl** [comment]
So I'm looking back at this, why would you not set the element's height and use scrollbarV?

**Comment by amiller29au** [comment]
@amcdnl - I am using scrollbarV option only all my grids. I tried setting the element's height but because the bodyHeight was set to 300, it would only render 5 rows, it didn't matter what I had tried.

**Comment by amcdnl** [comment]
See if it works now in 0.7.4. I think it was a bug I fixed last night

**Comment by amiller29au** [comment]
Sorry this did not work, I changed the height of the table using css and number of rows displayed to not increase.

**Comment by amcdnl** [comment]
Can u make a demo of what u are seeing? I can't seem to repo this.

**Comment by amiller29au** [comment]
Ok all good this now working. You could remove redundant code.

**Pull request merged**
