### PR TITLE
Fix issue when column height when column value is null

### PR DESCRIPTION
**Pull request by amiller29au**
The column height is not correct when column value is null.

Main issue here is specifying column borders in stylesheet when value is null, the column border is only rendered for the top part of the column not the full height.

### CODE REVIEW

**Comment by amcdnl** [comment]
We probably need to add this- https://github.com/swimlane/angular2-data-table/blob/master/src/components/body/BodyCell.ts#L40 and add a check for if its Nan too not to append the px.

**Comment by amiller29au** [comment]
I agree need to add the px suffix or we could simple do @HostBinding('style.width.px') without the need to specify the units in the method.

Not sure how the check if Nan would not append the height to the host element.

**Comment by amcdnl** [comment]
If you wanna update just to do that manually for now, I will merge.

**Comment by amiller29au** [comment]
Will do

**Pull request merged**
